BolsaDeEmprego/config/routes.rb
BolsaDeEmprego::Application.routes.draw do

  get "newsletter/new"
  get "password_resets/new"
  get "password_resets/edit"
  resources :oferta

  resources :candidatos

  resources :entidades
  #  resources :interesses

  resources :noticia, path: 'backoffice/noticia'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, path: 'backoffice/users'
  resources :password_resets,     only: [:new, :create, :edit, :update]


  match 'backoffice/:id/editpassword',  to: 'users#editpassword',       via: 'get',     as: 'editpassword_user'
  match '/:id/editpassword',            to: 'users#editpasswordFO',     via: 'get',     as: 'editpassword_frontoffice_user'
  match '/:id/updatePassword',          to: 'users#updatePassword',     via: 'put'
  match 'noticia',                      to: 'noticia#indexFrontOffice', via: 'get',     as: 'noticia_frontoffice'
  match 'noticia/:id',                  to: 'noticia#showFrontOffice',  via: 'get',     as: 'noticium_frontoffice'
  match '/',                            to: 'home#index',               via: 'get',     as: 'home'
  match 'backoffice/',                  to: 'home#indexBackOffice',     via: 'get',     as: 'home_backoffice'
  match 'candidatos/profile/:id',       to: 'candidatos#profile',       via: 'get',     as: 'candidato_profile'
  match 'entidades/profile/:id',        to: 'entidades#profile',        via: 'get',     as: 'entidade_profile'
  match 'interesseD/:id',               to: 'interesse#destroy',        via: 'delete',  as: 'del_interesse'
  match 'interesseC/:id',               to: 'interesse#create',         via: 'post',    as: 'cre_interesse'
  match 'candidaturaC/:id',             to: 'candidatura#create',       via: 'post',    as: 'cre_candidatura'
  match 'candidaturaD/:id',             to: 'candidatura#destroy',      via: 'delete',  as: 'del_candidatura'
  match 'oferta/activar_oferta/:id',    to: 'oferta#activar',           via: 'post',    as: 'activar_oferta'
  match 'oferta/desactivar_oferta/:id', to: 'oferta#desactivar',        via: 'delete',  as: 'desactivar_oferta'
  match '/signin',                      to: 'sessions#new',             via: 'get'
  match '/signup',                      to: 'users#regist',             via: 'get'
  match '/signout',                     to: 'sessions#destroy',         via: 'delete'
  root  'sessions#home'
end



#namespace :backoffice do
#  resources :noticia,
#  :users do
#        member do
#          get :editpassword
#        end
#      end
#end

BolsaDeEmprego/app/controllers/noticia_controller.rb
class NoticiaController < ApplicationController
  before_action :is_logged, except: [:indexFrontOffice,:showFrontOffice]
#before_action :set_noticium, only: [:show, :edit, :update, :destroy]


  def index
    @noticia = Noticium.all
  end

  def show
    @noticium = Noticium.find(params[:id])
  end

  def indexFrontOffice
    @noticium = Noticium.all
    @noticias = @noticium.where("activo=true").paginate(page: params[:page], :per_page => 10, :order => "destaque DESC, data DESC")
  end

  def showFrontOffice
    @noticium = Noticium.find(params[:id])
  end

  def new
    @noticium = Noticium.new
  end

  def edit
    @noticium = Noticium.find(params[:id])
  end

  def create
    @noticium = Noticium.new(noticium_params)
    Rails.logger.debug("---->My object: #{@noticium.inspect}")

      if @noticium.save
        flash[:success] = "Noticia registada"
        redirect_to @noticium
      else
        render 'new'
      end

  end

  def update
    @noticium = Noticium.find(params[:id])

    if @noticium.update_attributes(noticium_params)
      flash[:success] = "Noticia actualizada"
      redirect_to @noticium
    else
      render 'edit'
    end
  end


  def destroy
    @noticium.destroy
    respond_to do |format|
      format.html { redirect_to noticia_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_noticium
      @noticium = Noticium.find(params[:id])
    end

    def is_logged
      if(!signed_in?)
        render :file => 'public/permition.html', :layout => false
      else
        user = User.find(current_user.id)
        tipouser = TipoUser.find(user.tipo_user_id)

        if(tipouser.designacao != 'admin')
          render :file => 'public/permition.html', :layout => false
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def noticium_params
      params.require(:noticium).permit(:titulo, :sumario, :data, :texto, :imagem, :destaque, :activo)
    end
end

BolsaDeEmprego/app/helpers/noticia_helper.rb
module NoticiaHelper
  def toPT(user)
    if user == true
      "Sim"
    else
      "Não"
    end
  end
end

BolsaDeEmprego/app/views/noticia/_form.html.erb
<%= tinymce_assets %>
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>
<script>
$(function() {
  var minDate = new Date();
     $( ".datepicker" ).datepicker({
    defaultDate: minDate,
    changeMonth: true,
    changeYear: true,
    dateFormat: "dd-mm-yy",
  });
});
</script>
<%= simple_form_for @noticium do |f| %>
<%= f.error_notification %>
  <!-- <% if @noticium.errors.any? %>
  <div class="row">
    <div class="span12 offset1">
       <ul>
        <% @noticium.errors.full_messages.each do |message| %>
          <li style="display:block;color:red;"><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
  <% end %> -->

<div class="row">
  <div class="span6 offset1">
      <div class="form-inputs">
        <%= f.label :titulo, 'Titulo'%>
        <%= f.input :titulo, label: false %>
      </div>

  </div>
  <div class="span6 offset1">
    <%= f.label :data, 'Data'%>
    <%= f.text_field :data, :class => "datepicker","data-provide" => 'datepicker', label: false %>
    <span class="help-block"><%= show_errors(@noticium, :data) %></span>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :sumario, 'Sumário'%>
        <%= f.text_area :sumario, :class => "tinymce", :rows => 7, :cols => 120, label: false %>
        <span class="help-block"><%= show_errors(@noticium, :sumario) %></span>
      </div>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :texto, 'Texto'%>
        <%= f.text_area :texto, :class => "tinymce", :rows => 7, :cols => 120, label: false %>
        <span class="help-block"><%= show_errors(@noticium, :texto) %></span>
      </div>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
          <%= f.label :imagem, 'Imagem'%>
          <%= f.input :imagem, as: :file, label: false %>
      </div>
  </div>
</div>

<div class="row">
  <div class="span6 offset1">
      <div class="form-inputs">
          <%= f.label :destaque, 'Destaque'%>
          <%= f.check_box :destaque, {}, '1', '0' %>
          Aparece em destaque

      </div>
  </div>
  <div class="span6 offset1">
    <div class="form-inputs">
        <%= f.label :activo, 'Activo'%>
        <%= f.check_box :activo, {}, '1', '0' %>
        Sim
    </div>
  </div>

</div>


  <div class="form-actions">
    <%= f.button :submit %>
  </div>
  <%= link_to 'Back', noticia_path %>
<% end %>
<%= tinymce %>

BolsaDeEmprego/app/views/noticia/edit.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Editar Noticia</h2>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Cancelar', :back %>

BolsaDeEmprego/app/views/noticia/index.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Notícias</h2>
  </div>
</div>
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>
<div class="row">
  <div class="span12 offset1">
    <input type="text" id="search" value="" onkeyup="updateSearchSimple()">
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
    <table>
      <thead>
        <tr>
          <th>Notícia</th>
          <th>Data</th>
          <th>Destaque</th>
          <th>Activo</th>
          <th>Acções</th>
        </tr>
      </thead>

      <tbody>
        <% @noticia.each do |noticium| %>
          <tr>
            <td><%= noticium.titulo %></td>
            <td><%= noticium.data %></td>
            <td><%= toPT(noticium.destaque)%></td>
            <td><%= toPT(noticium.activo)%></td>
            <td>
              <%= link_to 'Detalhes', noticium_path(noticium), :class => "btn" %>
              <%= link_to 'Editar', edit_noticium_path(noticium), :class => "btn"  %>
              <%= link_to 'Apagar', noticium, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

<%= link_to 'Inserir', new_noticium_path, :class => "btn" %>
</div>
</div>

BolsaDeEmprego/app/views/noticia/indexFrontOffice.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Noticias</h2>
  </div>
</div>

<div class="row">
  <% @noticias.each do |noticia| %>
  <div class="span6 offset1">
    <div class="span2 offset0">
        <%= image_tag noticia.imagem.url %>
    </div>
    <div class="span3 offset0">
    <% if noticia.destaque %>
      <%= link_to noticia.titulo+"(Em Destaque)", noticium_frontoffice_path(noticia) %>
    <% else %>
      <%= link_to noticia.titulo, noticium_frontoffice_path(noticia) %>
    <% end %>
  </br>
    <%= noticia.data%></br>
    <%= noticia.sumario[0..100].html_safe %>
    </div>
  </div>
  <% end %>
</div>

<%= will_paginate @noticias, :remote => true %>

BolsaDeEmprego/app/views/noticia/new.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Nova Noticia</h2>
  </div>
</div>

<%= render 'form' %>

BolsaDeEmprego/app/views/noticia/show.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Detalhe da Noticia</h2>
  </div>
</div>
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>
  <div class="row">
    <div class="span6 offset1">
      <p>
        <strong>Titulo:</strong>
      </p>
      <p>
        <%= @noticium.titulo %>
      </p>
    </div>
    <div class="span6 offset1">
      <p>
        <strong>Data:</strong>
      </p>
      <p>
        <%= @noticium.data %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="span12 offset1">
      <p>
        <strong>Sumário:</strong>
      </p>
      <p>
        <%= @noticium.sumario.html_safe %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="span12 offset1">
      <p>
        <strong>Texto:</strong>
      </p>
      <p>
        <%= @noticium.texto.html_safe %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="span12 offset1">
      <p>
        <strong>Imagem:</strong>
      </p>
      <p>
        <%= image_tag @noticium.imagem.url%>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="span6 offset1">
      <p>
        <strong>Destaque:</strong>
      </p>
      <p>
        <%= toPT(@noticium.destaque) %>
      </p>
    </div>
    <div class="span6 offset1">
      <p>
        <strong>Activo:</strong>
      </p>
      <p>
        <%= toPT(@noticium.activo) %>
      </p>
    </div>
  </div>
<div class="row">
  <div class="span12 offset1">
    <%= link_to 'Edit', edit_noticium_path(@noticium), :class => "btn" %>
    <%= link_to 'Apagar', @noticium, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
    <%= link_to 'Inserir', new_noticium_path, :class => "btn" %>
    <%= link_to 'Listagem', noticia_path, :class => "btn" %>
  </div>
</div>

BolsaDeEmprego/app/views/noticia/showFrontOffice.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2><%= @noticium.titulo %></h2>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
    <%= @noticium.data %>
  </div>
</div>
<div>
<div class="row">
  <div class="span12 offset1">
      <%= image_tag @noticium.imagem.url,:class => "noticia-imagem" %>
      <p style="text-align: justify; text-indent: 2em;"><%= @noticium.texto.html_safe %>
    </p>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
<%= link_to 'Ver Todas'.html_safe, noticia_frontoffice_path %>
</div>
</div>
</div>