BolsaDeEmprego/config/routes.rb
BolsaDeEmprego::Application.routes.draw do

  get "newsletter/new"
  get "password_resets/new"
  get "password_resets/edit"
  resources :oferta

  resources :candidatos

  resources :entidades
  #  resources :interesses

  resources :noticia, path: 'backoffice/noticia'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, path: 'backoffice/users'
  resources :password_resets,     only: [:new, :create, :edit, :update]


  match 'backoffice/:id/editpassword',  to: 'users#editpassword',       via: 'get',     as: 'editpassword_user'
  match '/:id/editpassword',            to: 'users#editpasswordFO',     via: 'get',     as: 'editpassword_frontoffice_user'
  match '/:id/updatePassword',          to: 'users#updatePassword',     via: 'put'
  match 'noticia',                      to: 'noticia#indexFrontOffice', via: 'get',     as: 'noticia_frontoffice'
  match 'noticia/:id',                  to: 'noticia#showFrontOffice',  via: 'get',     as: 'noticium_frontoffice'
  match '/',                            to: 'home#index',               via: 'get',     as: 'home'
  match 'backoffice/',                  to: 'home#indexBackOffice',     via: 'get',     as: 'home_backoffice'
  match 'candidatos/profile/:id',       to: 'candidatos#profile',       via: 'get',     as: 'candidato_profile'
  match 'entidades/profile/:id',        to: 'entidades#profile',        via: 'get',     as: 'entidade_profile'
  match 'interesseD/:id',               to: 'interesse#destroy',        via: 'delete',  as: 'del_interesse'
  match 'interesseC/:id',               to: 'interesse#create',         via: 'post',    as: 'cre_interesse'
  match 'candidaturaC/:id',             to: 'candidatura#create',       via: 'post',    as: 'cre_candidatura'
  match 'candidaturaD/:id',             to: 'candidatura#destroy',      via: 'delete',  as: 'del_candidatura'
  match 'oferta/activar_oferta/:id',    to: 'oferta#activar',           via: 'post',    as: 'activar_oferta'
  match 'oferta/desactivar_oferta/:id', to: 'oferta#desactivar',        via: 'delete',  as: 'desactivar_oferta'
  match '/signin',                      to: 'sessions#new',             via: 'get'
  match '/signup',                      to: 'users#regist',             via: 'get'
  match '/signout',                     to: 'sessions#destroy',         via: 'delete'
  root  'sessions#home'
end



#namespace :backoffice do
#  resources :noticia,
#  :users do
#        member do
#          get :editpassword
#        end
#      end
#end

BolsaDeEmprego/app/models/candidato.rb
class Candidato < ActiveRecord::Base
  belongs_to :user, inverse_of: :candidato
  validates :user_id, presence: true
  belongs_to :area_prof, inverse_of: :candidato, :class_name => 'AreaProfissional'
  validates :area_prof_id, presence: true
  accepts_nested_attributes_for :area_prof
  belongs_to :habilitacao, inverse_of: :candidato, :class_name => 'NHabilitacoes'
  validates :habilitacao_id, presence: true
  belongs_to :situacao_prof, inverse_of: :candidato, :class_name => 'SituacaoProfissional'
  validates :situacao_prof_id, presence: true
  belongs_to :concelho, inverse_of: :candidato, :class_name => 'Concelho'
  validates :concelho_id, presence: true

  has_many :candidaturas
  has_many :ofertas, :class_name => 'Ofertum', through: :candidaturas

  has_attached_file :foto
  validates :foto, attachment_presence: true
  validates_attachment_content_type :foto, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
  validates :cv, attachment_presence: true
  has_attached_file :cv


  def existCandidaturaPara?(oferta)
    candidaturas.find_by(oferta_id: oferta.id)
  end

  def candidatar!(oferta)
    candidaturas.create!(oferta_id: oferta.id)
  end

  def retirarCandidatura!(oferta)
    candidaturas.find_by(oferta_id: oferta.id).destroy
  end

  VALID_CODPOSTAL_REGEX = /\A[0-9]{4}\-[0-9]{3}\z/i
  VALID_DATA_REGEX = /\A[0-9]{4}\-[0-9]{2}\-[0-9]{2}\z/i
  VALID_PAGINA_REGEX = /\A[a-z\d\-.]+\.[a-z]+\z/i


  validates :morada, presence: true, length: { maximum: 50,  too_long: "Morada demasiado comprida" }
  validates :data, format: { with: VALID_DATA_REGEX, message: "Respeite o formato da data (ex:dd-mm-yyyy)" }
  validates :apresentacao, length: { minimum: 10,  too_short: "Apresentação demasiado curta"}
  validates :habilitacoes, length: { minimum: 10,  too_short: "Habilitações deverá conter pelo menos 10 caracteres"}
  validates :exp_profissional, length: { minimum: 10,  too_short: "Experiencia Profissional deverá conter pelo menos 10 caracteres"}
  validates :codigoPostal, format: { with: VALID_CODPOSTAL_REGEX, message: "Respeite o formato do codigo postal (ex:4590-123)" }
  validates :pagina, format: { with: VALID_PAGINA_REGEX, message: "Respeite o formato do endereço web (ex:algo.dominio)" }

  validates :contacto, presence: true, :inclusion => { :in => 100000000..999999999, :message => "O contacto telefonico tem 9 digitos obrigatórios" }
  validates :contactoSec, :inclusion => { :in => 100000000..999999999, :message => "O contacto telefonico alternativo tem 9 digitos obrigatórios", :allow_nil => true }
  validates :bi, presence: true, :inclusion => { :in => 10000000..99999999, :message => "O BI tem 8 digitos obrigatórios" }

  after_initialize do
    self.user ||= self.build_user()

    #Rails.logger.debug("---->My object43: #{( AreaProfissional.find(self.area_prof_id) ).attributes.inspect}")
    self.area_prof ||= self.build_area_prof()
    self.situacao_prof ||= self.build_situacao_prof()
    self.habilitacao ||= self.build_habilitacao()
    self.concelho ||= self.build_concelho()

    #Rails.logger.debug("---->My object2: #{(self.area_prof ).inspect}")
  end

  def self.search(search,area,stituacao, concelho)
    query = ""
    if !search || search.length==0
      query = "true"
    else
      query = "(nome LIKE '%#{search}%' OR apresentacao LIKE '%#{search}%' OR habilitacoes LIKE '%#{search}%'  OR exp_profissional LIKE '%#{search}%')"
    end
    query = query + " AND "

    if !area || area.length ==0
      query = query + "true"
    else
      query = query + "area_prof_id = '#{area}'"
    end

    query = query + " AND "

    if !stituacao || stituacao.length ==0
      query = query + "true"
    else
      query = query + "situacao_prof_id = '#{area}'"
    end

    query = query + " AND "

    if !concelho || concelho.length ==0
      query = query + "true"
    else
      query = query + "concelho_id = '#{concelho}'"
    end
    joins(:user).where(query)
  end
end

BolsaDeEmprego/app/controllers/candidatos_controller.rb
class CandidatosController < ApplicationController
  before_action :is_logged, except: [:index,:show,:new, :create]

  # GET /candidatos
  # GET /candidatos.json
  def index
    if !params[:search] && !params[:area] && !params[:situacao] && !params[:concelho]
      @candidatos = Candidato.where("activo=true").search("","","","").paginate(:per_page => 8, :page => params[:page])
    else
      @candidatos = Candidato.where("activo=true").search(params[:search],params[:area][:id], params[:situacao][:id],params[:concelho][:id]).paginate(:per_page => 8, :page => params[:page])
    end
  end

  # GET /candidatos/1
  # GET /candidatos/1.json
  def profile
    @candidato = Candidato.find(params[:id])
    @user=@candidato.user
    @other_user = Entidade.find(1).user
  end


  # GET /candidatos/1
  # GET /candidatos/1.json
  def show
    @candidato = Candidato.find(params[:id])
  end

  # GET /candidatos/new
  def new
    @candidato = Candidato.new
    @candidato.build_user
    @candidato.build_area_prof
    @user = User.new
  end

  # GET /candidatos/1/edit
  def edit
    @candidato = Candidato.find(params[:id])
    @user=User.find(@candidato.user_id)

    @candidato.user=User.find(@candidato.user_id)
    @candidato.build_user
    #@candidato.build_area_prof

  end

  # POST /candidatos
  # POST /candidatos.json
  def create
    @tipo_user_id = TipoUser.find_by(designacao: "candidato").id
    @user = User.new(user_params.merge(tipo_user_id: @tipo_user_id,))
    @user.activo = true
    @user.subscription_newsletter=true
    @candidato = Candidato.new(candidato_params)
    @candidato.valid?
    Rails.logger.debug("---->My object2: #{( @candidato.errors.full_messages).inspect}")


  if @user.save
      @candidato = Candidato.new(candidato_params.merge(user_id: @user.id))

        if @candidato.save

          flash[:success] = "Registado com sucesso"
          redirect_to signin_path
        else
          User.delete(@user.id)
          render "new"
        end
    else
      render "new"
    end
  end

  # PATCH/PUT /candidatos/1
  # PATCH/PUT /candidatos/1.json
  def update
    @candidato = Candidato.find(params[:id])
    @user = User.find(@candidato.user_id)

    if @user.update_attributes(user_params)
      if @candidato.update_attributes(candidato_params)
        flash[:success] = "Perfil Actualizado"
        redirect_to @candidato
      else
        render 'edit'
      end
    else
      render 'edit'
    end
  end

  # DELETE /candidatos/1
  # DELETE /candidatos/1.json
  def destroy

  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_candidato
      @candidato = Candidato.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
        params.require(:candidato).require(:user).permit(:nome, :email, :password, :password_confirmation, :subscription_newsletter )
    end
    def candidato_params
        params.require(:candidato).permit(:user_id, :morada, :foto, :codigoPostal, :concelho_id, :contacto, :contactoSec, :pagina, :bi, :apresentacao, :area_prof_id, :cv,:habilitacao_id, :habilitacoes, :situacao_prof_id, :exp_profissional, :data)
    end

    def is_logged
      if(!signed_in?)
        render :file => 'public/permition.html', :layout => false
      else
        user = User.find(current_user.id)
        tipouser = TipoUser.find(user.tipo_user_id)

        if(tipouser.designacao != 'candidato' && tipouser.designacao != 'admin')
          render :file => 'public/permition.html', :layout => false
        end
      end
    end
end

BolsaDeEmprego/app/helpers/candidatos_helper.rb
module CandidatosHelper
end

BolsaDeEmprego/app/views/candidatos/_candidatos.html.erb
<div class="row">
<% @candidatos.each do |candidato| %>
  <div class="span6 offset1" style="margin-bottom:20px;">
    <div class="span2 offset0">
        <%= image_tag candidato.foto.url%>
    </div>
    <div class="span3 offset0">
    <div class="row">
    <%= link_to candidato.user.nome, candidato_path(candidato) %>
  </div>
    <div class="row">
      <%=  candidato.area_prof.designacao%>
    </div>
      <div class="row">
      <%= candidato.exp_profissional[0..100].html_safe %>
    </div>
    </div>
    <div class="row">
      <div class="span6 offset0" style="margin-top:14px;">
        <% if currentUserIsEntidade? %>
          <% if current_user.following?(candidato.user) %>
              <%= link_to "Não Interessado", del_interesse_path(candidato.user.id), :class => "btn", :method => :delete,remote: true %>
          <% else %>
              <%= link_to "Interessado", cre_interesse_path(candidato.user.id), :class => "btn", :method => :post,remote: true %>
          <% end %>
        <% end %>
        <% if currentUserIsAdmin? || currentUserIsCandidato? %>
          <%= link_to "Edit", edit_candidato_path(candidato), :class => "btn" %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>
<%= will_paginate @candidatos, :remote => true %>

BolsaDeEmprego/app/views/candidatos/_form.html.erb
<%= tinymce_assets %>
<script>
  $(function() {
    var minDate = new Date();
    var maxDate = new Date();
       $( ".datepicker" ).datepicker({
      defaultDate: minDate,
      changeMonth: true,
      changeYear: true,
      dateFormat: "dd-mm-yy",
      maxDate: maxDate,
    });
  });
</script>
<%= simple_form_for @candidato do |f| %>
  <%= f.error_notification %>
    <!-- <% if @candidato.errors.any? %>
    <div class="row">
      <div class="span12 offset1">
         <ul>
          <% @candidato.errors.full_messages.each do |message| %>
            <li style="display:block;color:red;"><%= message %></li>
          <% end %>
        </ul>
      </div>
    </div>
    <% end %> -->
  <%= f.fields_for @user do |u| %>


  <div class="row">
    <div class="span6 offset1">
        <div class="form-inputs">
          <%= f.label :email, 'Email'%>
          <%= u.input :email, label: false %>
        </div>
    </div>
      <div class="span6 offset1">
            <p>
              <label>Subscrever newsletter:</label>
            </p>
            <p>
            <%= u.check_box :subscription_newsletter, {}, '1', '0' %>  </p>
      </div>
  </div>
  <div class="row">
    <div class="span6 offset1">
        <div class="form-inputs">
          <%= f.label :password, 'Password'%>
           <%= u.input :password, label: false %>
        </div>
    </div>
    <div class="span6 offset1">
        <div class="form-inputs">
          <%= f.label :email, 'Confirmar Password'%>
           <%= u.input :password_confirmation, label: false %>
        </div>
    </div>
  </div>
  <div class="row">
    <div class="span6 offset1">
        <div class="form-inputs">
          <%= f.label :nome, 'Nome'%>
           <%= u.input :nome, label: false %>
        </div>
    </div>
 <% end %>
    <div class="span6 offset1">
      <%= f.label :foto, 'Foto'%>
      <%= f.input :foto, as: :file, label: false %>
    </div>
  </div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :morada, 'Morada'%>
        <%= f.input :morada, label: false %>
      </div>

  </div>
</div>
<div class="row">
  <div class="span6 offset1">
      <div class="form-inputs">

        <div class="form-inputs">
          <%= f.label :codigoPostal, 'Codigo Postal'%>
          <%= f.input :codigoPostal, label: false %>
        </div>
      </div>
  </div>
  <div class="span6 offset1">
      <div class="form-inputs">

        <div class="form-inputs">
          <%= f.label :concelho_id, 'Localidade'%>
          <%=  f.collection_select :concelho_id, Concelho.order(:designacao),:id,:designacao, include_blank: false, label: false  %>
        </div>
        </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="span6 offset1">
      <div class="form-inputs">

        <div class="form-inputs">
          <%= f.label :contacto, 'Contacto'%>
          <%= f.input :contacto, label: false %>
        </div>
        <div class="form-inputs">
          <%= f.label :contactoSec, 'Contacto Alternativo'%>
          <%= f.input :contactoSec, label: false %>
        </div>
      </div>
  </div>
  <div class="span6 offset1">
      <div class="form-inputs">

        <div class="form-inputs">
          <%= f.label :pagina, 'Pagina'%>
          <%= f.input :pagina, label: false %>
        </div>
      </div>
  </div>
</div>
<div class="row">
  <div class="span6 offset1">
    <div class="form-inputs">
      <%= f.label :data, 'Data de nascimento'%>
      <%= f.text_field :data, :class => "datepicker","data-provide" => 'datepicker', label: false %>
      <span class="help-block"><%= show_errors(@candidato, :data) %></span>
    </div>
  </div>
  <div class="span6 offset1">
    <div class="form-inputs">
      <%= f.label :bi, 'BI'%>
      <%= f.input :bi, label: false %>
    </div>
  </div>
</div>
<div class="row">
  <div class="span6 offset1">
    <div class="form-inputs">
      <%= f.label :cv, 'Curriculum Vitae'%>
      <%= f.input :cv, as: :file, label: false %>
    </div>
  </div>
  <div class="span6 offset1">
    <div class="form-inputs">
      <%= f.label :area_prof_id, 'Area Profissional'%>
      <%=  f.collection_select :area_prof_id, AreaProfissional.order(:designacao),:id,:designacao, include_blank: false, label: false  %>
    </div>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :apresentacao, 'Apresentação'%>
        <%= f.text_area :apresentacao, :class => "tinymce", :rows => 7, :cols => 120, label: false %>
<span class="help-block"><%= show_errors(@candidato, :apresentacao) %></span>
      </div>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :habilitacao_id, 'Habilitação'%>
        <%=  f.collection_select :habilitacao_id, NHabilitacoes.order(:designacao),:id,:designacao, include_blank: false, label: false  %>
      </div>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :habilitacoes, 'Habilitações'%>
        <%= f.text_area :habilitacoes, :class => "tinymce", :rows => 7, :cols => 120, label: false %>
        <span class="help-block"><%= show_errors(@candidato, :habilitacoes) %></span>
      </div>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :situacao_prof_id, 'Situação Profissional'%>
        <%=  f.collection_select :situacao_prof_id, SituacaoProfissional.order(:designacao),:id,:designacao, include_blank: false, label: false  %>
      </div>
  </div>
</div>
<div class="row">
  <div class="span12 offset1">
      <div class="form-inputs">
        <%= f.label :exp_profissional, 'Experiencia Profissional'%>
        <%= f.text_area :exp_profissional, :class => "tinymce", :rows => 7, :cols => 120, label: false %>
        <span class="help-block"><%= show_errors(@candidato, :exp_profissional) %></span>
      </div>
  </div>
</div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

BolsaDeEmprego/app/views/candidatos/edit.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Editar Candidato</h2>
  </div>
</div>
<%= render 'form' %>

<%= link_to 'Show', @candidato %> |
<%= link_to 'Back', candidatos_path %>

BolsaDeEmprego/app/views/candidatos/index.html.erb
<div class="row">
  <div class="span12 offset1">
    <h3>Candidatos</h3>
  </div>
</div>
<script>
$(function() {
  $("#candidatos_search p input").keyup(function() {
    //$(this.form).submit()
    $("#candidatos_search").submit()
    //$.get($("#candidatos_search").attr("action"), $("#candidatos_search").serialize(), null, "script");
    return false;
  });
  $('#search_drop1').on('change', function(){
  $("#candidatos_search").submit()
  });

  $('#search_drop2').on('change', function(){
  $("#candidatos_search").submit()
  });

  $('#search_drop3').on('change', function(){
    $("#candidatos_search").submit()
  });
});
</script>

<div class="row">
  <div class="span12 offset1">
    <%= form_tag candidatos_path, :method => 'get', :id => "candidatos_search", remote:true do %>
      <p>
        <%= text_field_tag :search, params[:search] %>
        <% if !params[:area]%>
        <%=   collection_select :area, :id, AreaProfissional.order(:designacao),:id,:designacao, {:include_blank => 'Area de Atividade'}, {:id => "search_drop1",label: false }  %>
        <% else %>
        <%=   collection_select :area, :id, AreaProfissional.order(:designacao),:id,:designacao, {:include_blank => 'Area de Atividade',:selected => params[:area][:id]}, {:id => "search_drop1",label: false }  %>
        <% end %>
        <% if !params[:situacao]%>
        <%=   collection_select :situacao, :id, SituacaoProfissional.order(:designacao),:id,:designacao, {:include_blank => 'Situacao Profissional'}, {:id => "search_drop2",label: false }  %>
        <% else %>
        <%=   collection_select :situacao, :id, SituacaoProfissional.order(:designacao),:id,:designacao, {:include_blank => 'Situacao Profissional',:selected => params[:situacao][:id]}, {:id => "search_drop2",label: false }  %>
        <% end %>
        <% if !params[:concelho]%>
        <%=   collection_select :concelho, :id, Concelho.order(:designacao),:id,:designacao, {:include_blank => 'Concelho'}, {:id => "search_drop3",label: false }  %>
        <% else %>
        <%=   collection_select :concelho, :id, Concelho.order(:designacao),:id,:designacao, {:include_blank => 'Concelho',:selected => params[:concelho][:id]}, {:id => "search_drop3",label: false }  %>
        <% end %>
        <%= submit_tag "Search", :name => nil %>
      </p>
    <% end %>
  </div>
</div>



  <div id="candidatos"><%= render 'candidatos' %></div>



  <div class="row">
    <div class="span12 offset1">
        <%= link_to 'Quero-me registar', signup_path %>
    </div>
  </div>

BolsaDeEmprego/app/views/candidatos/index.js.erb
$("#candidatos").html("<%= escape_javascript(render("candidatos")) %>");

BolsaDeEmprego/app/views/candidatos/new.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Registar Candidato</h2>
  </div>
</div>

<%= render 'form' %>

<%= link_to 'Back', candidatos_path %>

BolsaDeEmprego/app/views/candidatos/profile.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Perfil - <%=@candidato.user.nome%></h3>
  </div>
</div>
<div class="row">
  <div class="span8 offset1">
    <h3>Candidaturas</h3>
      <% @candidato.candidaturas.each do |cand| %>
        <div class="row">
          <div class="span2">
            <%= image_tag cand.oferta.foto.url%></br>
          </div>
          <div class="span4">
              <div class="span4">
              <%= link_to cand.oferta.titulo, ofertum_path(cand.oferta) %>
              </div>
              <div class="span4">
                <%= cand.oferta.dataI %> a <%= cand.oferta.dataF %>
              </div>
              <div class="span4">
                <%= cand.oferta.descricao[0..100].html_safe %>
              </div>
          </div>
        </div>
      <% end %>

    <h3>empresas interessados em mim</h3>
    <% @candidato.user.interessadosEmMim.each do |inte| %>
      <div class="row">
        <div class="span2">
          <%= image_tag inte.entidade.foto.url%></br>
        </div>
        <div class="span4">
            <div class="span4">
            <%= link_to inte.nome, entidade_path(inte.entidade.id) %>
            </div>
            <div class="span4">
              <%= inte.entidade.apresentacao[0..100].html_safe %>
            </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="span6 offset1">
    <div>
      <h3>Candidato</h3>
    </div>
    <div>
    <%= link_to "Editar dados", edit_candidato_path(@candidato.id), :class => "btn" %>
    <%= link_to "Alterar Password", editpassword_frontoffice_user_path(@candidato.user.id), :class => "btn" %>
    </div>
  </div>
</div>

BolsaDeEmprego/app/views/candidatos/show.html.erb
<div class="row">
  <div class="span12 offset1">
    <h3><%=@candidato.user.nome%></h3>
  </div>
</div>
<div class="row">
  <div class="span2 offset1">
    <div>
      <%= image_tag @candidato.foto.url, :style => "margin-left: auto;margin-right: auto;"%>
    </div>
    <div class="row" style="text-align:center;margin-top:14px;margin-left: auto;margin-right: auto;">
      <%= link_to  "Curriculum Vitae",  @candidato.cv.url(:original, false) %>
    </div>
    <div class="row" style="text-align:center;margin-top:14px;margin-left: auto;margin-right: auto;">
      <% if currentUserIsEntidade? %>
        <% if current_user.following?(@candidato.user) %>
            <%= link_to "Não Interessado", del_interesse_path(@candidato.user.id), :class => "btn", :method => :delete,remote: true %>
        <% else %>
            <%= link_to "Interessado", cre_interesse_path(@candidato.user.id), :class => "btn", :method => :post,remote: true %>
        <% end %>
      <% end %>
    </div>
    <div class="row" style="text-align:center;margin-top:14px;margin-left: auto;margin-right: auto;">
      <% if currentUserIsAdmin? || currentUserIsCandidato? %>
        <%= link_to "Edit", edit_candidato_path(@candidato), :class => "btn" %>
      <% end %>
    </div>
  </div>

  <div class="span9 offset1">
    <div class="row">
      <p>
        <%=@candidato.apresentacao.html_safe %>
      </p>

    </div>
    <div class="row">
      <p>
        <strong>Atividade Profissional:</strong></br>
        <%=@candidato.area_prof.designacao %>
      </p>
    </div>
    <div class="row">
        <h3>Dados Profissionais</h3>
    </div>
    <div class="row">
      <p>
        <strong>Situação Profissional:</strong></br>
        <%=@candidato.situacao_prof.designacao %>
      </p>
    </div>
    <div class="row">
      <p>
        <strong>Nivel Habilitações:</strong></br>
        <%=@candidato.habilitacao .designacao  %>
      </p>
    </div>

    <div class="row">
      <p>
        <strong>Habilitações Literárias:</strong></br>
        <%=@candidato.habilitacoes.html_safe %>
      </p>
    </div>
    <div class="row">
      <p>
        <strong>Experiencia Profissional:</strong></br>
        <%=@candidato.exp_profissional.html_safe %>
      </p>
    </div>
  </br>
    <div class="row">
        <h3>Dados Pessoais</h3>
    </div>
    <div class="row">
      <p>
        <strong>Morada:</strong></br>
        <%=@candidato.morada %>
      </p>
    </div>
    <div class="row">
      <p>
        <strong>Contactos:</strong></br>
        <%=@candidato.contacto %></br>
        <%=@candidato.contactoSec %>
      </p>
    </div>
    <div class="row">
      <%= link_to @candidato.pagina, extlink(@candidato.pagina), :target => "_blank" %>
    </div>
  </div>
</div>

<div class="row">
  <div class="span12 offset1">
    <%= link_to 'Ver Candidatos', candidatos_path %>
  </div>
</div>