BolsaDeEmprego/config/routes.rb
BolsaDeEmprego::Application.routes.draw do

  get "newsletter/new"
  get "password_resets/new"
  get "password_resets/edit"
  resources :oferta

  resources :candidatos

  resources :entidades
  #  resources :interesses

  resources :noticia, path: 'backoffice/noticia'
  resources :sessions, only: [:new, :create, :destroy]
  resources :users, path: 'backoffice/users'
  resources :password_resets,     only: [:new, :create, :edit, :update]


  match 'backoffice/:id/editpassword',  to: 'users#editpassword',       via: 'get',     as: 'editpassword_user'
  match '/:id/editpassword',            to: 'users#editpasswordFO',     via: 'get',     as: 'editpassword_frontoffice_user'
  match '/:id/updatePassword',          to: 'users#updatePassword',     via: 'put'
  match 'noticia',                      to: 'noticia#indexFrontOffice', via: 'get',     as: 'noticia_frontoffice'
  match 'noticia/:id',                  to: 'noticia#showFrontOffice',  via: 'get',     as: 'noticium_frontoffice'
  match '/',                            to: 'home#index',               via: 'get',     as: 'home'
  match 'backoffice/',                  to: 'home#indexBackOffice',     via: 'get',     as: 'home_backoffice'
  match 'candidatos/profile/:id',       to: 'candidatos#profile',       via: 'get',     as: 'candidato_profile'
  match 'entidades/profile/:id',        to: 'entidades#profile',        via: 'get',     as: 'entidade_profile'
  match 'interesseD/:id',               to: 'interesse#destroy',        via: 'delete',  as: 'del_interesse'
  match 'interesseC/:id',               to: 'interesse#create',         via: 'post',    as: 'cre_interesse'
  match 'candidaturaC/:id',             to: 'candidatura#create',       via: 'post',    as: 'cre_candidatura'
  match 'candidaturaD/:id',             to: 'candidatura#destroy',      via: 'delete',  as: 'del_candidatura'
  match 'oferta/activar_oferta/:id',    to: 'oferta#activar',           via: 'post',    as: 'activar_oferta'
  match 'oferta/desactivar_oferta/:id', to: 'oferta#desactivar',        via: 'delete',  as: 'desactivar_oferta'
  match '/signin',                      to: 'sessions#new',             via: 'get'
  match '/signup',                      to: 'users#regist',             via: 'get'
  match '/signout',                     to: 'sessions#destroy',         via: 'delete'
  root  'sessions#home'
end



#namespace :backoffice do
#  resources :noticia,
#  :users do
#        member do
#          get :editpassword
#        end
#      end
#end

BolsaDeEmprego/app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :reset_token
    before_save { self.email = email.downcase }


    belongs_to :tipo_user, inverse_of: :user, :class_name => 'TipoUser'
    validates :tipo_user_id, presence: true

    has_one :entidade, inverse_of: :user, :class_name => 'Entidade', :foreign_key => 'user_id', dependent: :destroy
    accepts_nested_attributes_for :entidade
    has_one :candidato, inverse_of: :user, :class_name => 'Candidato', :foreign_key => 'user_id', dependent: :destroy
    accepts_nested_attributes_for :candidato


    has_many :interesses, :class_name => 'Interesse', foreign_key: "origem_id", dependent: :destroy
    has_many :interessadoEm, through: :interesses, source: :destino
    has_many :reverse_interesses, foreign_key: "destino_id",
                                     class_name:  "Interesse",
                                     dependent:   :destroy
    has_many :interessadosEmMim, through: :reverse_interesses, source: :origem



    validates :nome, presence: true, length: { maximum: 50,  too_long: "Nome demasiado comprido" }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, format: { with: VALID_EMAIL_REGEX, message: "Respeite o formato do email (exemplo@fornecedor.dominio)"},
                       uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, length: { minimum: 6,  too_short: "Password demasiado curta (Insegura)"},  :if => :password



    def following?(other_user)
      interesses.find_by(destino_id: other_user.id)
    end

    def follow!(other_user)
      interesses.create!(destino_id: other_user.id)
    end

    def unfollow!(other_user)
      interesses.find_by(destino_id: other_user.id).destroy
    end


    def User.new_remember_token
      SecureRandom.urlsafe_base64
    end

    def User.digest(token)
      Digest::SHA1.hexdigest(token.to_s)
    end

    # Sets the password reset attributes.
    def create_reset_digest
    self.reset_token = User.new_remember_token
      update_attribute(:reset_digest,  User.digest(reset_token))
      update_attribute(:reset_sent_at, Time.zone.now)
    end




    after_initialize do
      self.tipo_user ||= self.build_tipo_user()
    end

    private

  end

BolsaDeEmprego/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :is_logged, except: [:regist,:editpasswordFO,:updatePassword]

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @tipo = TipoUser.find(@user.tipo_user_id)
    @activo = ""
    if @user.activo == true
      @activo = "Sim"
    else
      @activo = "Não"
    end
  end

  def new
    @user = User.new
  end

  def regist

  end


  def edit
      @user = User.find(params[:id])
      @tipo = TipoUser.find(@user.tipo_user_id)
  end

  def editpasswordFO
    if(!signed_in?)
      render :file => 'public/permition.html', :layout => false
    else
      if(current_user.id != params[:id].to_i)
        render :file => 'public/permition.html', :layout => false
      end
    end
    @user = User.find(params[:id])
    @tipo = TipoUser.find(@user.tipo_user_id)

  end

  def editpassword
      @user = User.find(params[:id])
      @tipo = TipoUser.find(@user.tipo_user_id)
  end

  def create
    @tipo_user_id = TipoUser.find_by(designacao: "admin").id
    @user = User.new(user_params.merge(password: '123456', password_confirmation: '123456',tipo_user_id: @tipo_user_id))                                             #################Atualizar
    #@user.activo = 1;
    if @user.save
      flash[:success] = "Bem vindo"
      redirect_to @user
    else

      render 'new'
    end
  end

  def update

    @user = User.find(params[:id])
    params[:user].delete(:password) if params[:user][:password].blank?
    params[:user].delete(:password_confirmation) if params[:user][:password_confirmation].blank?
    if @user.update_attributes(user_params)
      flash[:success] = "Perfil Actualizado"
      redirect_to @user
    else
          Rails.logger.debug("---->My object2: #{( @user.errors.full_messages).inspect}")
      render 'edit'
    end
  end

  def updatePassword
    if(!signed_in?)
      render :file => 'public/permition.html', :layout => false
    else
      if(current_user.id != params[:id].to_i)
        render :file => 'public/permition.html', :layout => false
      end
    end
    @user = User.find(params[:id])

    if @user && @user.authenticate(params[:user][:passwordActual])
      if @user.update_attributes(user_params)
        flash[:success] = "Perfil Actualizado"
        if(current_user.tipo_user.designacao=="entidade")
          redirect_to entidade_profile_path(current_user.entidade.id)
        else
          if(current_user.tipo_user.designacao=="candidato")
              redirect_to candidato_profile_path(current_user.candidato.id)
          end
        end
      else
        render 'editpasswordFO'
      end
    else
      @user.errors.add(:passwordActual, "Introduza a password actual")
      render 'editpasswordFO'
    end
  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "Utilizador Eliminado"
    redirect_to :controller => 'users', :action => 'index'

  end

  private

    def user_params
      params.require(:user).permit(:nome, :email, :password,
                                   :password_confirmation, :activo, :subscription_newsletter )
    end

    def is_logged
      if(!signed_in?)
        render :file => 'public/permition.html', :layout => false
      else
        user = User.find(current_user.id)
        tipouser = TipoUser.find(user.tipo_user_id)

        if(tipouser.designacao != 'admin')
          render :file => 'public/permition.html', :layout => false
        end
      end
    end
end

BolsaDeEmprego/app/helpers/users_helper.rb
module UsersHelper


  def toPT(user)
    if user == true
      "Sim"
    else
      "Não"
    end
  end
    def getDesignacao(user)
      TipoUser.find(user).designacao
  end
end

BolsaDeEmprego/app/views/users/_form.html.erb
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>
<%= simple_form_for(@user) do |f| %>
  <%= f.error_notification %>
    <div class="row">
      <div class="span6 offset1">
        <%= f.input :nome, placeholder: 'Introduza o nome' %>
      </div>
      <div class="span6 offset1">
        <p>
          <label>Tipo:</label>
        </p>
        <p>
          Backoffice
        </p>
      </div>
    </div>
    <div class="row">
      <div class="span6 offset1">
        <%= f.input :email, placeholder: 'Introduza o email' %>
      </div>
      <div class="span6 offset1">
        <p>
          <label>Activo:</label>
        </p>
      <%= f.check_box :activo, {}, '1', '0' %>
    </div>
    </div>
  </div><div class="row">
    <div class="span12 offset1">
          <p>
            <label>Subscrever newsletter:</label>
          </p>
          <p>
          <%= f.check_box :subscription_newsletter, {}, '1', '0' %>  </p>
    </div>
  </div>
    <div class="row">
      <div class="span12 offset1">
        <%= f.submit "Submeter", class: "btn btn-large btn-primary" %>
      </div>
    </div>
  <% end %>

BolsaDeEmprego/app/views/users/edit.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Editar utilizador</h2>
  </div>
</div>

<%= render 'form' %>

BolsaDeEmprego/app/views/users/editpassword.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Alterar Password</h2>
  </div>
</div>
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>
<div class="row">
    <%= simple_form_for(@user) do |f| %>

    <div class="span12 offset1">
      <p>
        <label> Nome:</label>
      </p>
      <p>
      <%= @user.nome %>
      </p>
    </div>
    <div class="span12 offset1">
      <%= f.input :password, placeholder: 'Introduza a password' %>
    </div>
    <div class="span12 offset1">
      <%= f.input :password_confirmation, placeholder: 'Introduza novamente a password' %>
    </div>
    <div class="span12 offset1">
      <%= f.submit "Gravar", class: "" %>
    </div>
    <% end %>
</div>

BolsaDeEmprego/app/views/users/editpasswordFO.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Alterar Password</h2>
  </div>
</div>

<div class="row">
    <%= simple_form_for(@user, :url => { :action => "updatePassword" }, :html => { :method => :put }) do |f| %>

    <div class="span12 offset1">
      <p>
        <label> Nome:</label>
      </p>
      <p>
      <%= @user.nome %>
      </p>
    </div>
    <div class="span12 offset1">
      <%= f.input :passwordActual, placeholder: 'Introduza a password actual' %>
    </div>
    <div class="span12 offset1">
      <%= f.input :password, placeholder: 'Introduza a nova password' %>
    </div>
    <div class="span12 offset1">
      <%= f.input :password_confirmation, placeholder: 'Introduza novamente a nova password' %>
    </div>
    <div class="span12 offset1">
      <%= f.submit "Gravar", class: "" %>
    </div>
    <% end %>
</div>

BolsaDeEmprego/app/views/users/index.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Utilizadores</h2>
  </div>
</div>
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>
<div class="row">
  <div class="span12 offset1">
    <input type="text" id="search" value="" onkeyup="updateSearch()">
    <select id="searchType" onchange="updateSearch()">
    <option value="Nome">Nome</option>
    <option value="Tipo">Tipo</option>
    <option value="Activo">Activo</option>
  </select>
  </div>
</div>


<div class="row">
  <table class="span12 offset1">
    <thead>
      <tr>
        <th>Nome</th>
        <th>Tipo</th>
        <th>Activo</th>
        <th>Acções</th>
      </tr>
    </thead>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.nome %></td>
          <td><%= getDesignacao(user.tipo_user_id) %></td>
          <td><%= toPT(user.activo)%></td>


          <td>
            <%= link_to 'Detalhes', user_path(user), :class => "btn" %>
            <%= link_to 'Editar', edit_user_path(user), :class => "btn"  %>
            <%= link_to 'Apagar', user, method: :delete, :class => "btn", data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<div class="row">
  <div class="span12 offset1">
    <%= link_to 'Inserir', new_user_path, :class => "btn" %>

</div>
</div>

BolsaDeEmprego/app/views/users/new.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Registo do utilizador</h2>
  </div>
</div>

<%= render 'form' %>

BolsaDeEmprego/app/views/users/regist.html.erb
<div class="row">
  <div class="span12 offset1">
    <h3>Novo Registo</h3>
  </div>
</div>

<div class="row">
  <div class="span12 offset1" style="margin-top:30px">
    <%= link_to "Sou uma entidade", new_entidade_path, :class => "btn btn-extralarge" %>
  </div>
</div>
<div class="row">
  <div class="span12 offset1" style="margin-top:30px">
    <%= link_to "Sou um candidato", new_candidato_path, :class => "btn btn-extralarge" %>
  </div>
</div>

BolsaDeEmprego/app/views/users/show.html.erb
<div class="row">
  <div class="span12 offset1">
    <h2>Detalhe do utilizador</h2>
  </div>
</div>
<div id="flash">
  <% if notice.present? %>
    <%= render partial: "shared/notice_banner" %>
  <% end %>
</div>
  <div class="row">
    <div class="span6 offset1">
      <p>
        <strong>Nome:</strong>
      </p>
      <p>
        <%= @user.nome %>
      </p>
    </div>
    <div class="span6 offset1">
      <p>
        <strong>Tipo:</strong>
      </p>
      <p>
        <%= @tipo.designacao %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="span6 offset1">
      <p>
        <strong>Email:</strong>
      </p>
      <p>
        <%= @user.email %>
      </p>
    </div>
    <div class="span6 offset1">
      <p>
        <strong>Activo:</strong>
      </p>
      <p>
        <%= @activo%>
      </p>
    </div>
  </div>
<div class="row">
  <div class="span12 offset1">
    <%= link_to 'Edit', edit_user_path(@user), :class => "btn" %>
    <%= link_to 'Alterar Password', editpassword_user_path(@user), :class => "btn" %>
    <%= link_to 'Apagar',  @user, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn" %>
    <%= link_to 'Inserir', new_user_path, :class => "btn" %>
    <%= link_to 'Listagem', users_path, :class => "btn" %>
  </div>
</div>